### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by coyotte508** [boardgamers/powergrid#11]
> In this game:
> https://www.boardgamers.space/game/Feb15SpainnoJim
> 
> The blue player had plants 10/25/33 with two coal.  When #40 was bought, #10 was discarded and the coal was removed.  The coal should have been moved to plant 25
> 
> Please check into that

**Comment by LucasAMello** [comment]
Could not reproduce, maybe the player chose to discard the resources on purpose? Check #7
