### ISSUE TITLE
Broken replay feature

### ISSUE THREAD

**Issue by tjohnson314** [boardgamers/powergrid#13]
The replay feature on the site doesn't work very well. The log includes three different kinds of items (LogPhase, LogEvent, LogMove), but only the LogMove items are returned in the replay.

That means that when I try to step through the replay from the beginning, it gets stuck at the first item that isn't a LogMove.

I think a simple fix is to replace the current replay function in the wrapper with a call to engine.reconstructState. But I haven't been able to test it, since I haven't figured out how to run the site locally with a local build of the Powergrid game.

**Comment by coyotte508** [comment]
> But I haven't been able to test it, since I haven't figured out how to run the site locally with a local build of the Powergrid game.

Check out https://docs.boardgamers.space/

The site uses https://docs.boardgamers.space/guide/engine-api.html#replay to replay, which is defined in `engine/wrapper.ts`:

- https://github.com/boardgamers/powergrid/blob/master/engine/wrapper.ts
- https://github.com/boardgamers/boardgamers-mono/blob/master/apps/game-server/app/routes/gameplay.ts#L63

So you should be able to more or less test it without running the site directly by using the functions in `wrapper.ts`. A potential issue is that not all data is sent to a player (for example, the hidden cards in the factory deck or the money of other players).

A full working build is available on https://gitpod.io/#https://github.com/boardgamers/boardgamers-mono - you need to wait a bit before everything is loaded (even after the loading screen is gone, a minute or so) but then you can open the site on port 8612 & admin on port 3000. The admin user is `admin@test.com` with password `password`.

Anyway, you can reach me on discord as well (the discord link in the announcement), I'd be happy to help anything regarding development.
