### ISSUE TITLE
three plants available step 1

### ISSUE THREAD

**Issue by mmunson99** [boardgamers/powergrid#22]
In this game, there are only three available to buy:
https://www.boardgamers.space/game/France-6players

**Comment by LucasAMello** [comment]
Bug related to france setup, should be correct now.

**Comment by mmunson99** [comment]
yes, thanks

    On Monday, March 14, 2022, 03:45:57 PM PDT, Lucas Mello ***@***.***> wrote:  
 
 


Bug related to france setup, should be correct now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
