### ISSUE TITLE
undoing a build

### ISSUE THREAD

**Issue by mmunson99** [boardgamers/powergrid#24]
In this game:
https://www.boardgamers.space/game/bof
Steffen_86 asked about undoing a build

**Comment by coyotte508** [comment]
This is more of something that should be askedon the discord (#feedback-powergrid) channel as it's not a bug report (or even a feature request)

**Comment by mmunson99** [comment]
sorry - I thought that undo was supposed to be allowed, so it seemed like it was a bug if undo was not working

    On Wednesday, March 16, 2022, 08:25:13 AM PDT, Eliott C. ***@***.***> wrote:  
 
 


This is more of something that should be askedon the discord (#feedback-powergrid) channel as it's not a bug report (or even a feature request)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by coyotte508** [comment]
My bad - I thought you were asking bout rewinding the game. If the undo is broken, it's indeed the correct place to ask :sweat_smile:
