### ISSUE TITLE
Dropped player can't pass

### ISSUE THREAD

**Issue by coyotte508** [boardgamers/powergrid#3]
JSON: https://gist.github.com/eliott-playplay/f18654e4e7bdf7f644fc2e1616c077ba

Trying to drop the player fails with:

![image](https://user-images.githubusercontent.com/342922/145683662-fd9ddb46-9940-4eb2-89e4-e771a0b83ad7.png)

**Comment by LucasAMello** [comment]
When a player is dropped it tries to Pass, but in that case Passing was not a possible move. I've changed it to use the AI to choose the next move when passing is not an option.
