### ISSUE TITLE
undo error

### ISSUE THREAD

**Issue by mmunson99** [boardgamers/powergrid#30]
in this game, someone clicked undo and ended up with 10 trash:
https://www.boardgamers.space/game/Milky-ether-8898

**Comment by LucasAMello** [comment]
No idea what happened here... the log shows the player used the same power plant three times, I tried replicating the bug but no luck.
@coyotte508 This was a live game so maybe something to do with simultaneous requests?
One of the users had some weird mongodb erros:
https://admin.boardgamers.space/user/goldjohn6

**Comment by coyotte508** [comment]
There is a lock to prevent simulatenous access on the DB object - this is what the mongo error is. It prevents two players from doing something at the same time.

So it shouldn't be that...

**Comment by LucasAMello** [comment]
There was a bug when undoing a "User Power Plant" move. I'm not 100% sure but maybe it will fix this issue.
