### ISSUE TITLE
table order

### ISSUE THREAD

**Issue by mmunson99** [boardgamers/powergrid#40]
We use the turn order for most of the game and use table order for the auction.  In this game:
https://www.boardgamers.space/game/FranceMay17
most of us could see the table order correctly

KVkristina said the table order was resorted each time to match the turn order, but that made the auction confusing for KVkristina

![image0(2)](https://user-images.githubusercontent.com/101267272/168932223-256d6b0f-4ce5-458b-87a4-125bb6b828b5.jpeg)

I tried to attach a screen shot here showing what KVkrisitina was seeing, which was different from what others saw

**Comment by LucasAMello** [comment]
There's a user setting to control that, they probably had it on
![image](https://user-images.githubusercontent.com/35138524/168940350-62ca83f9-a400-449f-af43-17dd8dd0618e.png)

**Comment by mmunson99** [comment]
thanks

    On Tuesday, May 17, 2022, 06:47:24 PM PDT, Lucas Mello ***@***.***> wrote:  
 
 


Closed #40.
