### ISSUE TITLE
Unable to start Gaia Games

### ISSUE THREAD

**Issue by theagricolan** [boardgamers/powergrid#61]
I currently have three Gaia Project games that are open. The only commonality is that all three games involved player invitations. Even after all invited players joined, the game is stuck on the invitation screen and won’t start. Looking at the lobby, it appears there are more in the same boat.

**Comment by NicolasAubinet** [comment]
Yes, same here. Game never starts.

**Comment by coyotte508** [comment]
Sorry for the issue.

Can you check if the problem still happens?

**Comment by NicolasAubinet** [comment]
Game has successfully started now! Thanks for the fix
